/** Occasional ambient lines in the game channel (playful but clean tone). */

import { IDLE_RPG_VERSION } from '../config.js';

const LINES = [
  'The ledger is live. Silence is still the fastest strategy.',
  'Friendly reminder: commands starting with ! do not add message penalty.',
  'Use PM for account actions: REGISTER and LOGIN.',
  'Need a quick status check? Try !whoami.',
  'Need realm status? Try !realm.',
  'Need recent events? Try !chronicle.',
  'Need records? Try !records.',
  'Need your timer? Try !time.',
  'Need all commands? !cmds is your friend.',
  'Quest points only count while you are online and visible in channel.',
  'Parting while logged in can hurt your timer. The ledger notices.',
  'Logout also has a timer cost. Use it when needed, not by reflex.',
  'Lucky hour can flip your pace. Keep an eye on !realm.',
  'Hand of God is generous until it is not.',
  'Duel is optional. Regret is not.',
  'Gauntlet is optional. Cooldown is guaranteed.',
  'Omen can bless, curse, or simply troll your expectations.',
  'Your cooldown summary is in !whoami.',
  'Two heroes enter duel chat, one leaves with a better timer.',
  'Gauntlet: your shadow has no mercy and no keyboard.',
  'In this game, typing less is a valid optimization.',
  'This is one of the few places where patience is a power stat.',
  'Yes, idling is gameplay. No, this is not a bug.',
  'The leaderboard reads the same SQLite ledger as the bot.',
  'Every penalty is deterministic. Every outcome still feels personal.',
  'Your next level is a quiet contract with time.',
  'RNG appears when it wants. Mostly when you are confident.',
  'Quest teams care about uptime, not speeches.',
  'Medals do not make you faster. They make your history shinier.',
  'If you forget syntax, !help has your back.',
  'If you forget details, !cmds has your backup.',
  'Duel target in range? Great. Duel cooldown active? Also great.',
  'Gauntlet cooldown teaches patience the hard way.',
  'Omen cooldown exists to protect everyone from fate spam.',
  'One quiet minute now is one less complaint later.',
  'Stay logged in, stay visible, stay calm.',
  'The channel is social. The timer is business.',
  'Realm pulse is one line. Consequences are many.',
  'There is no pay-to-win. Only wait-to-win.',
  'If in doubt, do less. This game rewards that.',
  'A short message now can cost a longer wait later.',
  'Every level is earned one second at a time.',
  'Consistency beats spikes in this economy.',
  'A duel win is nice. A clean idle streak is nicer.',
  'The chronicle never sleeps, it only appends.',
  'Keep your nick stable if you value your timer.',
  'The quiet path still works. Always has.',
  'You can be chatty or you can be early to level.',
  'System status: clocks running, hopes high.',
  'Alert: your future self prefers fewer penalties.',
  `${IDLE_RPG_VERSION} online. Timer economy stable.`,
  'NetIRC classic mode: fewer words, faster progress.',
  'A well-timed command beats ten random messages.',
  'If duel hurts today, idle still pays tomorrow.',
  'If gauntlet hurts today, cooldown protects tomorrow.',
  'If omen hurts today, at least the story improved.',
  'Quest up, heads down.',
  'Clock discipline is an actual build here.',
  'This shard rewards quiet confidence.',
  'The best macro is still patience.',
];

export function randomChannelBanter(): string {
  return LINES[Math.floor(Math.random() * LINES.length)]!;
}
