/** Occasional ambient lines in the game channel (IdleRPG / NetIRC vibe). */

import { IDLE_RPG_VERSION } from '../config.js';

const LINES = [
  'The ledger ticks. Only silence compounds interest here.',
  'In this realm, every spoken word taxes destiny. !rules for the quiet path.',
  'NetIRC watches. Idle heroes, your timers are running.',
  'Shh. Someone out there is about to level.',
  'The bot remembers every penalty and every patient second. Stay sharp — or stay silent.',
  '!help · !top · !stats — free whispers in channel. Normal lines cost time.',
  'Classic IdleRPG energy: less chat, more legend.',
  'Hand of God might bless you. Or roast your ping. Such is life on IRC.',
  'REGISTER / LOGIN in private. The channel is for the grind, not the signup desk.',
  'Silence isn’t empty — it’s the main quest.',
  'The scoreboard at idlerpg.netirc.eu reads the same SQLite the bot does.',
  'Part the channel while logged in? The timer feels that. So does your pride.',
  'Level caps are for other games. Here, the ceiling is your patience.',
  'One day you’ll explain to a normie that typing less was how you won.',
  'IRC never died. It leveled up in the shadows.',
  'Whisper LOGIN to me if you dare return to the idle throne.',
  'Even forests and rangers need to shut up sometimes. Especially rangers.',
  'The realm hums on port 6667. The drama runs on pure quiet.',
  'Penalties are temporary. Levels are… also temporary. But cooler.',
  'Your next level is a stack of seconds. No microtransactions. Just time.',
  `${IDLE_RPG_VERSION} — where AFK is a competitive sport.`,
  'Someone just tallied another idle minute. Was it you?',
  'The channel topic is optional. The timer is not.',
  'When words fail, try !duel — same channel, same ledger, different kind of quiet.',
  'The chronicle grows one line at a time. !chronicle if gossip is your poison.',
  'Quest teams don’t care how witty you are — only how long you’ve gone quiet.',
  '⌛ Every second in channel is a coin in the idle bank. Spend words wisely.',
  'RNG blessed someone today. Was it you? Check !realm.',
  'The lucky hour window opens like a thief — blink and you missed the pulse.',
  '!gauntlet — fight your own shadow. Spoiler: the shadow also idles.',
  'Badges don’t make you faster; they make you louder in the scrollback.',
  'Two heroes, one arena, zero excuses. !duel if you’re brave and bored.',
  'Silence is a class feature. Multiclassing into “chatty” has penalties.',
  'The SQLite file is the one true oracle. Everything else is flair.',
  'Idle is not passive. It’s strategic non-typing.',
  'Omen cooldown exists so fate doesn’t spam you back.',
  'If you’re reading this line, you’re paying time tax. Unless it starts with !',
  'The realm record stands until someone out-waits everyone else.',
  'Alignment shifts on Hog whims. Argue with the universe.',
  'Trinkets hum. The ledger knows. The timer doesn’t care.',
  'Moonveil and Sunbound are vibes, not vacation packages.',
  'Battle lines on the web map are decoration. The duel is real.',
  'Every logout leaves a scar on the timer — love your session.',
  'IRC nicks are capes. Character names are the myth stitched into SQLite.',
  'The bot notices when you vanish. So does your next_seconds.',
  'Patience isn’t a virtue here; it’s the entire build.',
  'One day the quest ends. Until then: shh.',
  'Level zero is honest. Every level after is a flex wrapped in math.',
  'NetIRC didn’t ask for heroes. It got you anyway.',
  'Your medal rack is proof you touched grass… digitally.',
  'Whisper HELP before you rage-quit the syntax.',
  'The idle grind: no loot boxes, just ticking clocks and spite.',
  'Someone is 1 second from leveling. It’s Schrödinger until it isn’t.',
  '!omen — the universe sends a postcard. Might be junk mail.',
  'Rangers, Paladins, Rogues — all equal under the penalty formula.',
  'The channel is a theater. Your timer is the critic.',
  'Stay logged in, stay visible, stay quiet. That’s the whole sermon.',
  'Hand of God rolls dice you never see. Welcome to the casino.',
  'Every !realm line is a heartbeat made of stats.',
  'If duel RNG hurts you today, remember: silence still levels you tomorrow.',
];

export function randomChannelBanter(): string {
  return LINES[Math.floor(Math.random() * LINES.length)]!;
}
